env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
    storage: "mysql"
    net: "tcp"
    address: "127.0.0.1"
    port: "3306"
    user: "root"
    password: "root"
    db_name: "todo"